//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSol {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblPre;
		
		protected System.Web.UI.WebControls.TextBox Pre;
		
		protected System.Web.UI.WebControls.Label lblFirst;
		
		protected System.Web.UI.WebControls.TextBox first;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator firstNameValid;
		
		protected System.Web.UI.WebControls.Label lblLast;
		
		protected System.Web.UI.WebControls.TextBox last;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator lastNameValid;
		
		protected System.Web.UI.WebControls.Label lbSuffix;
		
		protected System.Web.UI.WebControls.TextBox Suffix;
		
		protected System.Web.UI.WebControls.Label lblEmail;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqEmail;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator regexEmail;
		
		protected System.Web.UI.WebControls.Label lblConfirmEmail;
		
		protected System.Web.UI.WebControls.TextBox confirmEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqConfEmail;
		
		protected System.Web.UI.WebControls.CompareValidator compEmail;
		
		protected System.Web.UI.WebControls.Label lblPassword;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqPassword;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator regexPassword;
		
		protected System.Web.UI.WebControls.Label lblConfirmPassword;
		
		protected System.Web.UI.WebControls.TextBox confirmPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqConfPassword;
		
		protected System.Web.UI.WebControls.CompareValidator compPass;
		
		protected System.Web.UI.WebControls.Label lbPhone;
		
		protected System.Web.UI.WebControls.TextBox phone;
		
		protected System.Web.UI.WebControls.Label lblDescription;
		
		protected System.Web.UI.WebControls.DropDownList description;
		
		protected System.Web.UI.WebControls.TextBox pname;
		
		protected System.Web.UI.WebControls.TextBox acnym;
		
		protected System.Web.UI.WebControls.Label lbcontact;
		
		protected System.Web.UI.WebControls.TextBox proContact;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator proContactControl;
		
		protected System.Web.UI.WebControls.Label lbcontactemail;
		
		protected System.Web.UI.WebControls.TextBox proContactEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator proContactControlEmail;
		
		protected System.Web.UI.WebControls.Label lbcontactphone;
		
		protected System.Web.UI.WebControls.TextBox proContactPhone;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator proContactControlPhone;
		
		protected System.Web.UI.WebControls.Label lblSubject;
		
		protected System.Web.UI.WebControls.CheckBoxList subject;
		
		protected System.Web.UI.WebControls.Label lbother;
		
		protected System.Web.UI.WebControls.TextBox other;
		
		protected System.Web.UI.WebControls.Label lbGrade;
		
		protected System.Web.UI.WebControls.CheckBoxList grade;
		
		protected System.Web.UI.WebControls.Label lblProgDescription;
		
		protected System.Web.UI.WebControls.DropDownList Progdescription;
		
		protected System.Web.UI.WebControls.Label lbcost;
		
		protected System.Web.UI.WebControls.RadioButtonList radioCost;
		
		protected System.Web.UI.WebControls.TextBox exp;
		
		protected System.Web.UI.WebControls.Label lblduration;
		
		protected System.Web.UI.WebControls.RadioButtonList Progduration;
		
		protected System.Web.UI.WebControls.TextBox Additional_Notes;
		
		protected System.Web.UI.WebControls.Label lblseason;
		
		protected System.Web.UI.WebControls.RadioButtonList Season;
		
		protected System.Web.UI.WebControls.Label lbstartdate;
		
		protected System.Web.UI.WebControls.TextBox StartDate;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator StartDateControl;
		
		protected System.Web.UI.WebControls.Label lbAppDealine;
		
		protected System.Web.UI.WebControls.TextBox AppDeadline;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator AppDeadlineControl;
		
		protected System.Web.UI.WebControls.Label lbluniaff;
		
		protected System.Web.UI.WebControls.RadioButtonList UniAff;
		
		protected System.Web.UI.WebControls.Label lbOutReach;
		
		protected System.Web.UI.WebControls.RadioButtonList OutReach;
		
		protected System.Web.UI.WebControls.Label lbelig;
		
		protected System.Web.UI.WebControls.TextBox elig;
		
		protected System.Web.UI.WebControls.Label lbstreetaddress;
		
		protected System.Web.UI.WebControls.TextBox StreetAddress;
		
		protected System.Web.UI.WebControls.Label lbprogramcounty;
		
		protected System.Web.UI.WebControls.TextBox ProgramCounty;
		
		protected System.Web.UI.WebControls.Label lbprogramcity;
		
		protected System.Web.UI.WebControls.TextBox ProgramCity;
		
		protected System.Web.UI.WebControls.Label lbProgramZip;
		
		protected System.Web.UI.WebControls.TextBox ProgramZip;
		
		protected System.Web.UI.WebControls.Label lblserviceArea;
		
		protected System.Web.UI.WebControls.DropDownList ServiceArea;
		
		protected System.Web.UI.WebControls.Label lbProgSite;
		
		protected System.Web.UI.WebControls.TextBox ProgramSite;
		
		protected System.Web.UI.WebControls.TextBox ProgDes;
		
		protected System.Web.UI.WebControls.ValidationSummary validSummary;
		
		protected System.Web.UI.WebControls.Label lblSubmit;
		
		protected System.Web.UI.WebControls.Button BtnSubmit;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Label output;
		
		protected System.Web.UI.WebControls.Button Confirm;
	}
}
